-- -----------------------------------------------------
-- Table `ACCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACCOUNT`
(
  `ACCOUNT_ID`				VARCHAR(255),
  `EMAIL`					VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ACCOUNT_ID`)
);
-- -----------------------------------------------------
-- Table `PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUCT`
(
  `PRODUCT_ID`				VARCHAR(255),
  `PRODUCT_NAME`			VARCHAR(255) NOT NULL,
  `PRICE`					VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
);
-- -----------------------------------------------------
-- Table `RESERVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESERVE`
(
  `RESERVE_ID`				VARCHAR(255) generated by default as identity,
  `PRODUCT_ID`				VARCHAR(255) NOT NULL,
  `ACCOUNT_ID`					VARCHAR(255) NOT NULL,
  `RESERVE_FROM`	    TIMESTAMP NOT NULL,
  `RESERVE_TO`			TIMESTAMP NOT NULL,
  `CREATED_AT`				TIMESTAMP    NULL,
  `UPDATED_AT`				TIMESTAMP    NULL,
  PRIMARY KEY (`RESERVE_ID`)
);
ALTER TABLE `RESERVE`
    ADD FOREIGN KEY (`ACCOUNT_ID`) 
    REFERENCES ACCOUNT(`ACCOUNT_ID`);
ALTER TABLE `RESERVE`
    ADD FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES PRODUCT(`PRODUCT_ID`);